name: Build

on:
  repository_dispatch:
    types: [repo-released]

jobs:

  build:
    name: Build and Publish Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo_name }}
          ref: ${{ github.event.client_payload.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build AIMET
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker-util/Dockerfile
          tags: aimet:latest
          load: true
          build-args: |
            ARTIFACT_TAG=${{ github.event.client_payload.tag_name }}

      - name: Setup jFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}

      - name: Publish Docker Image
        run: | 
          jfrog --version
          jfrog rt ping
          jfrog rt docker-push codelinaro.jfrog.io/codelinaro-aimet/aimet:latest codelinaro-aimet
        
