name: Build

on:
  repository_dispatch:
    types: [changed-docker-file]

jobs:

  build:
    name: Build and Publish Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo_name }}
          ref: ${{ github.event.client_payload.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Parse Dockerfile
        env:
          file: ${{ github.event.client_payload.changed-docker-file }}
        run: |
          echo "BUILD_TYPE="$(echo ${file} | cut -d. -f2)"" >> $GITHUB_ENV

      - name: Build Dockerfile
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ${{ github.event.client_payload.changed-docker-file }}
          tags: artifacts.codelinaro.org/codelinaro-aimet/aimet:latest.${{ env.BUILD_TYPE }}
          load: true

      - name: Setup jFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}

      - name: Publish Docker Image
        run: |
          jfrog --version
          jfrog rt ping
          jfrog rt docker-push artifacts.codelinaro.org/codelinaro-aimet/aimet:latest.${{ env.BUILD_TYPE }} codelinaro-aimet
